// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJwzOlmWU2mxGptV7P4ZUg_H9LnFrt9K0',
    appId: '1:93051923835:web:d7d63857817b86c2d5e1de',
    messagingSenderId: '93051923835',
    projectId: 'demoauth-e286e',
    authDomain: 'demoauth-e286e.firebaseapp.com',
    storageBucket: 'demoauth-e286e.appspot.com',
    measurementId: 'G-E3T7WQM7WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZktluoCLHAUHDGUm2RlSFfPfk0zUFpEQ',
    appId: '1:93051923835:android:360d56f577a55ac1d5e1de',
    messagingSenderId: '93051923835',
    projectId: 'demoauth-e286e',
    storageBucket: 'demoauth-e286e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhYHZfv31vJeuajEbqwaHxBY-NYbBUp0',
    appId: '1:93051923835:ios:9372db8b3b07408bd5e1de',
    messagingSenderId: '93051923835',
    projectId: 'demoauth-e286e',
    storageBucket: 'demoauth-e286e.appspot.com',
    iosBundleId: 'com.example.demoLoginWithFacebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhYHZfv31vJeuajEbqwaHxBY-NYbBUp0',
    appId: '1:93051923835:ios:9372db8b3b07408bd5e1de',
    messagingSenderId: '93051923835',
    projectId: 'demoauth-e286e',
    storageBucket: 'demoauth-e286e.appspot.com',
    iosBundleId: 'com.example.demoLoginWithFacebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJwzOlmWU2mxGptV7P4ZUg_H9LnFrt9K0',
    appId: '1:93051923835:web:ab6b75711890f004d5e1de',
    messagingSenderId: '93051923835',
    projectId: 'demoauth-e286e',
    authDomain: 'demoauth-e286e.firebaseapp.com',
    storageBucket: 'demoauth-e286e.appspot.com',
    measurementId: 'G-CPMTG5H5WN',
  );
}
