// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCit-RQuNxeyCgbEXfDASfH6EwmM9oZfak',
    appId: '1:314026888702:web:4ce6e6637e23f4087f84af',
    messagingSenderId: '314026888702',
    projectId: 'facebookauthtest-93ec1',
    authDomain: 'facebookauthtest-93ec1.firebaseapp.com',
    storageBucket: 'facebookauthtest-93ec1.appspot.com',
    measurementId: 'G-2SVQGGEZD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZ5wr0r4-NoXfuDNM7dMtkHsOXwQcagw',
    appId: '1:314026888702:android:dc9658c7a461f1e67f84af',
    messagingSenderId: '314026888702',
    projectId: 'facebookauthtest-93ec1',
    storageBucket: 'facebookauthtest-93ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7OyuMPJKdKmpIvVU5ULy8RsIuTlAW7yo',
    appId: '1:314026888702:ios:7511ce8e23d0f8367f84af',
    messagingSenderId: '314026888702',
    projectId: 'facebookauthtest-93ec1',
    storageBucket: 'facebookauthtest-93ec1.appspot.com',
    iosBundleId: 'com.example.cafepia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7OyuMPJKdKmpIvVU5ULy8RsIuTlAW7yo',
    appId: '1:314026888702:ios:7511ce8e23d0f8367f84af',
    messagingSenderId: '314026888702',
    projectId: 'facebookauthtest-93ec1',
    storageBucket: 'facebookauthtest-93ec1.appspot.com',
    iosBundleId: 'com.example.cafepia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCit-RQuNxeyCgbEXfDASfH6EwmM9oZfak',
    appId: '1:314026888702:web:c757276d77c4fb687f84af',
    messagingSenderId: '314026888702',
    projectId: 'facebookauthtest-93ec1',
    authDomain: 'facebookauthtest-93ec1.firebaseapp.com',
    storageBucket: 'facebookauthtest-93ec1.appspot.com',
    measurementId: 'G-8HD0D4MPE9',
  );

}